name: ng2_dragula
version: 0.0.2
description: Drag and drop component for Angular 2 Dart.
author: Kasper Peulen <kasperpeulen@gmail.com>
homepage: https://github.com/kasperpeulen/ng2-dragula.git
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.2'
  dragula: '^0.0.4'
dev_dependencies:
  dart_to_js_script_rewriter: '^0.1.0+4'
  browser: '^0.10.0+2'
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter